name: Build and Publish

on:
  push:
    branches: [main]

jobs:
  build-and-push-image:
    env:
      IMAGE: ghcr.io/baetheus/pdf-bundle
    runs-on: ubuntu-latest

    steps:
      - name: Generate build ID
        id: prep
        run: |
          branch=${GITHUB_REF##*/}
          sha=${GITHUB_SHA::8}
          ts=$(date +%s)
          echo "::set-output name=BUILD_ID::${branch}-${sha}-${ts}"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image and push to Docker Hub and GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{ env.IMAGE }}:${{ steps.prep.outputs.BUILD_ID }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
